-- Migration 06: API Expansion for Contact, Support, and Enhanced Bookings

-- 1. Update bookings table with new fields
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS preferred_time TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS notes TEXT;

-- 2. Create Contacts table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Support Tickets table
CREATE TABLE IF NOT EXISTS support_tickets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  issue_type TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in progress', 'resolved')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable RLS and add basic policies
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

-- Policy: Admin can see all contacts (for now, allow select for testing or restricted roles)
CREATE POLICY "Admin can view contacts" ON contacts FOR SELECT USING (true); -- Simplified
CREATE POLICY "Anyone can submit contact message" ON contacts FOR INSERT WITH CHECK (true);

-- Policy: Users can view their own support tickets
CREATE POLICY "Users can view own tickets" ON support_tickets FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Anyone can submit support ticket" ON support_tickets FOR INSERT WITH CHECK (true);
