-- Migration 09: Production schema additions
-- Adds missing tables required by the API specification

-- 1. OTP Verifications
CREATE TABLE IF NOT EXISTS otp_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,
  otp_code TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_otp_phone ON otp_verifications(phone);

-- 2. Pricing Plans
CREATE TABLE IF NOT EXISTS pricing_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('home', 'commercial')),
  price NUMERIC NOT NULL,
  period TEXT,
  description TEXT,
  features JSONB NOT NULL DEFAULT '[]',
  is_featured BOOLEAN DEFAULT FALSE,
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Booking Status History
CREATE TABLE IF NOT EXISTS booking_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id UUID REFERENCES bookings(id) ON DELETE CASCADE,
  old_status TEXT,
  new_status TEXT NOT NULL,
  changed_by UUID,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_bsh_booking ON booking_status_history(booking_id);

-- 4. Site Stats
CREATE TABLE IF NOT EXISTS site_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  label TEXT,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Admin Settings
CREATE TABLE IF NOT EXISTS admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Add role column to profiles if not exists
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';

-- 7. Add customer fields to bookings for guest bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_phone TEXT;

-- 8. Enable RLS on new tables
ALTER TABLE otp_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_settings ENABLE ROW LEVEL SECURITY;

-- 9. RLS Policies
CREATE POLICY "Public can view pricing plans" ON pricing_plans FOR SELECT USING (true);
CREATE POLICY "Public can view site stats" ON site_stats FOR SELECT USING (true);
CREATE POLICY "Public can view testimonials" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Anyone can insert testimonials" ON testimonials FOR INSERT WITH CHECK (true);

-- 10. Seed pricing plans
INSERT INTO pricing_plans (name, type, price, period, description, features, is_featured, display_order) VALUES
  ('Basic Care', 'home', 1999, '/yr', 'Perfect for single-room cooling maintenance.', '["2 Wet Services", "Unlimited Breakdowns", "10% Off Spare Parts", "Priority Search"]', false, 1),
  ('Premium Shield', 'home', 3499, '/yr', 'Our most popular comprehensive protection.', '["3 Wet Services", "Free Gas Charging", "20% Off Spare Parts", "2-Hr Response Time"]', true, 2),
  ('Business Pro', 'commercial', 0, '', 'Scalable solutions for corporate offices.', '["Monthly Maintenance", "Dedicated Account Manager", "Free Spare Parts", "Bulk AC Management"]', false, 3)
ON CONFLICT DO NOTHING;

-- 11. Seed site stats
INSERT INTO site_stats (key, value, label) VALUES
  ('years_experience', '12+', 'Years of Excellence'),
  ('uptime', '99.9%', 'Uptime'),
  ('clients_served', '5000+', 'Happy Clients'),
  ('technicians', '50+', 'Expert Engineers')
ON CONFLICT (key) DO NOTHING;
