-- Migration 10: Reference Services
-- Adds services from the reference website

-- Create service_categories table
CREATE TABLE IF NOT EXISTS service_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT,
  display_order INT DEFAULT 0
);

-- Ensure we only insert if not exists
INSERT INTO service_categories (name, description, icon, display_order) VALUES
  ('AC Services', 'Complete air conditioner repair, installation and maintenance.', 'Wind', 1),
  ('Home Appliances', 'Expert repair for washing machines, refrigerators, microwaves and TVs.', 'Tv', 2)
ON CONFLICT (name) DO NOTHING;

-- Map existing services to AC category (assuming category is now a reference, wait, services table has `category` as TEXT in 02_seed_data.sql. Let's just use the TEXT field or alter it.)
-- Actually, the user asked for:
-- Core: AC Repair, AC Installation, AC Gas Refill, AC Maintenance, AC Uninstallation, Water leakage fix
-- Other: Washing Machine, Refrigerator, TV, Microwave

INSERT INTO services (category, title, description, price, original_price, features, icon, is_active) VALUES
  ('ac_services', 'AC Repair', 'Expert diagnostics and repair for all AC brands and models.', 499, 999, ARRAY['Complete diagnosis', 'Minor fault fixes', 'Guaranteed repair'], 'Wrench', true),
  ('ac_services', 'AC Installation', 'Professional split and window AC installation with standard materials.', 1499, 2199, ARRAY['Standard mounting', 'Pipe connection', 'Performance testing'], 'Wrench', true),
  ('ac_services', 'AC Uninstallation', 'Safe removal and uninstallation of your air conditioner.', 699, 1000, ARRAY['Gas pump down', 'Unit dismounting', 'Pipe capping'], 'Wrench', true),
  ('ac_services', 'AC Gas Refill', 'Refrigerant check and complete gas recharge with leak fixing.', 2499, 3500, ARRAY['Leak detection', 'Full gas recharge', 'Cooling check'], 'ShieldCheck', true),
  ('ac_services', 'AC Maintenance (Wet Servicing)', 'Deep cleaning of coils, filters, and drain lines for optimal cooling.', 599, 899, ARRAY['Coil washing', 'Filter cleaning', 'Drain unblocking'], 'Wind', true),
  ('ac_services', 'Water Leakage Fix', 'Immediate resolution of AC indoor unit water dripping issues.', 399, 699, ARRAY['Drain tray cleaning', 'Pipe unblocking', 'Slime removal'], 'Droplet', true),
  
  ('appliances', 'Washing Machine Repair', 'Front load, top load, and semi-automatic washing machine repairs.', 399, 799, ARRAY['Drum issues', 'Motor repair', 'PCB board fixing'], 'LifeBuoy', true),
  ('appliances', 'Refrigerator Repair', 'Single door, double door, and side-by-side fridge servicing.', 499, 899, ARRAY['Cooling issues', 'Gas refill', 'Compressor repair'], 'Thermometer', true),
  ('appliances', 'Microwave Repair', 'Fixing heating issues, keypad problems, and sparks in microwaves.', 299, 599, ARRAY['Magnetron replacement', 'Heating fix', 'Panel repair'], 'Zap', true),
  ('appliances', 'TV Repair', 'LED, LCD, and Smart TV screen, sound, and board repairing.', 599, 1299, ARRAY['Panel repair', 'Backlight fixing', 'Sound issues'], 'Monitor', true)
ON CONFLICT DO NOTHING;
